const productsData = [
    // === HEALTH CARE ===
    {
        id: "hc-1",
        category: "healthcare",
        name: "Elements Wellness Champi Champion Taila (200ml)",
        image: "images/healthcare/champicahmpion.jpeg",
        tag: "Health Support",
        descShort: "Ayurvedic massage oil for relaxation, muscle relief, and hair nourishment..",
        description: "A traditional herbal oil that helps reduce stiffness, improve skin texture, and support hair health.",
        ingredients: "Sesame Oil, Masha, Bala, Tea Tree Oil.",
        usage: "Warm slightly, massage into scalp or body, leave for 30–60 minutes, use twice a week.",
        features: "100% Plant-Based, Gluten-Free, Non-GMO, Free from Artificial Sweeteners.",
        price: "$540.00"
    },
    {
        id: "hc-2",
        category: "healthcare",
        name: "Elements Wellness Cof-Nil (100ml)",
        image: "images/healthcare/cofnil.jpeg",
        tag: "Immunity & Energy",
        descShort: "Ayurvedic cough syrup for soothing throat irritation and easing cough naturally.",
        description: " A 100% herbal formulation that helps relieve persistent cough, reduce throat irritation, and support respiratory comfort without causing drowsiness.ied and filtered to absolute purity.",
        ingredients: "Vasaka, Tulsi, Yasthimadhu (Yashti), Kantakari, Pippali.",
        usage: "Take up to 2 teaspoons in the morning and before bedtime or as directed by a physician.",
        features: "Third-party lab tested, Rich in 84+ minerals, No fillers, Hand-harvested.",
        price: "$200.00"
    },
    {
        id: "hc-3",
        category: "healthcare",
        name: "Elements Wellness Cyclova capsules",
        image: "images/healthcare/cyclova.jpeg",
        tag: "Digestive Wellness",
        descShort: "Ayurvedic capsules for supporting female hormonal balance and menstrual health.xquisite infusion of antioxidant herbs to support digestion, promote internal cleansing, and refresh your system.",
        description: "Ayurvedic capsules that support hormonal balance, ovarian health, and help regulate menstrual cycles, especially in PCOS.",
        ingredients: "Kanchanara, Hingu Suddha, Sariva, Varun, Shirisa, and other Ayurvedic herbs. ",
        usage: "Take 1–2 capsules twice daily after meals or as directed by a healthcare professional.",
        features: "Caffeine-Free, Biodegradable Pyramid Bags, Hand-sorted organic ingredients.",
        price: "$2062.00"
    },
    {
        id: "hc-4",
        category: "healthcare",
        badge: "",
        name: "Elements Wellness Below 37",
        image: "images/healthcare/below37.jpeg",
        tag: "Longevity",
        descShort: "Ayurvedic herbal supplement for reducing body heat and supporting immunity.",
        description: "Helps manage excess body heat, fever, cold, and cough symptoms while strengthening the body’s natural defense system.",
        ingredients: "Kalmegh, Guduchi (Giloy), Tulsi, Bilva, Chirayata, Pippali.",
        usage: "Take 1 capsule every 8 hours for the first two days of symptoms or as directed by a physician.",
        features: "Clinically proven bioavailability, Zero artificial color, Sugar-free.",
        price: "$938.00"
    },

    // === HOME CARE ===
    {
        id: "hm-1",
        category: "homecare",
        badge: "Luxury Choice",
        name: "Mi Home Floor Cleaner (500ml)",
        image: "images/homecare/floorcleaner.jpeg",
        tag: "Household Care",
        descShort: "Affordable floor cleaner that removes dirt, kills germs, and leaves a fresh fragrance.",
        description: "Effectively lifts dust, grime, and stains while providing up to 99% germ protection and a long-lasting fresh scent.",
        ingredients: "Surfactant-based cleaning agents with disinfectant and fragrance compounds.",
        usage: "Dilute in water and mop floors as usual for clean, sanitized, and streak-free surfaces.",
        features: "Pet-Safe, Biodegradable, Streak-Free, Recyclable Amber Glass Spray Bottle.",
        price: "$132.00"
    },
    {
        id: "hm-2",
        category: "homecare",
        badge: "",
        name: "Mi Home Glass Cleaner (500ml)",
        image: "images/homecare/glass cleaner.jpeg",
        tag: "Aromatherapy Mist",
        descShort: "Streak-free glass cleaner that removes fingerprints, dust, and smudges effectively.",
        description: "Quickly cuts through grime and oil marks on glass surfaces, leaving a clear, residue-free shine..",
        ingredients: "Solvent-based cleaning agents with fast-evaporating formula.",
        usage: "Spray on glass or mirror surfaces and wipe immediately with a clean cloth for a streak-free finish.",
        features: "Phthalate-Free, Stain-Free formula, Vegan, Long-lasting fragrance.",
        price: "$93.00"
    },
    {
        id: "hm-3",
        category: "homecare",
        badge: "",
        name: "Mi Home Liquid Laundry Detergent (500ml)",
        image: "images/homecare/maxbrite.jpeg",
        tag: "Household Care",
        descShort: "Enzyme-based liquid detergent that removes tough stains while keeping clothes soft and bright.",
        description: "Why should dishwashing dry out your hands? Formulated with soothing aloe vera extracts and refreshing eucalyptus essential oils, this concentrate cuts grease while offering an aromatic experience.",
        ingredients: "Sodium Lauroyl Sarcosinate, Aloe Vera Gel, Eucalyptus Essential Oil, Peppermint Extract, Sea Salt.",
        usage: "Pour a small coin-sized drop onto a wet sponge, squeeze to form rich lather, wash, and rinse thoroughly.",
        features: "pH balanced, Gentle on skin, Sulfate-free, Biodegradable.",
        price: "$242.00"
    },

    // === BEAUTY CARE ===
    {
        id: "bc-1",
        category: "beautycare",
        badge: "",
        name: "Elements Wellness 3-in-1 Face Wash (60g)",
        image: "images/Beautycare/3in1 facewash.jpeg",
        tag: "Facial Oil / Serum",
        descShort: "A 3-in-1 cleanser that removes oil, gently exfoliates, and helps control acne.",
        description: "Our signature facial oil combines the highest grade of handpicked Kashmiri Saffron with fine 24-karat gold leaf flakes. This luxury serum penetrates deep to fade dark spots, smooth fine lines, and impart a royal, radiant glow.",
        ingredients: "Kashmiri Kesar (Saffron), 24K Gold Dust, Sandalwood Oil, Almond Oil, Rosehip Seed Oil, Licorice Extract.",
        usage: "Apply 3-4 drops onto clean, damp face and neck. Gently press and massage in upward circular motions.",
        features: "Preservative-free, Cruelty-free, Fast-absorbing, Dermatologist tested.",
        price: "$198.00"
    },
    {
        id: "bc-2",
        category: "beautycare",
        badge: "",
        name: "Elements Wellness Anti-Dandruff Shampoo (200ml)",
        image: "images/Beautycare/antidanderuffshampoo.jpeg",
        tag: "Moisturizer",
        descShort: "Herbal shampoo that helps reduce dandruff and soothe itchy scalp.",
        description: "Quench your skin's thirst with Damascus Rose water and an advanced peptide complex. This cream builds a glassmorphic moisture barrier, locking in hydration for 72 hours for a plumped, dewy complexion.",
        ingredients: "Damascena Rose Distillate, Hexapeptide-8, Oligopeptide-1, Hyaluronic Acid, Shea Butter, Green Tea Extract.",
        usage: "Gently pat a dime-sized amount onto clean face and neck both morning and evening.",
        features: "Non-comedogenic, Paraben-free, Synthetic Fragrance-free.",
        price: "$332.00"
    },
    {
        id: "bc-3",
        category: "beautycare",
        badge: "",
        name: "Elements Wellness Ayuheel (50g)",
        image: "images/Beautycare/ayuheal.jpeg",
        tag: "Hair Care",
        descShort: "Ayurvedic foot cream for healing cracked heels and softening dry, rough skin.",
        description: "Infused with cold-pressed Moroccan Argan oil and rich Macadamia nut extracts, this luxury elixir transforms dull, damaged strands into silky, flowing tresses while protecting against heat styling.",
        ingredients: "Argan Kernel Oil, Macadamia Seed Oil, Vitamin E, Sweet Almond Oil, Jojoba Seed Oil, Jasmine Absolute.",
        usage: "Apply a few drops to palms and distribute evenly through clean, towel-dried hair, focusing on mid-lengths to ends.",
        features: "Silicone-free, Mineral oil-free, UV protectant properties.",
        price: "$226.00"
    },
    {
        id: "bc-4",
        category: "beautycare",
        badge: "Grooming",
        name: "Elements Wellness 8 in 1 Hair Conditioner (100ml)",
        image: "images/Beautycare/conditionerelemnets.jpeg",
        tag: "Grooming Essential",
        descShort: "Multi-action conditioner that nourishes hair, reduces frizz, and improves softness.",
        description: "Crafted with pure Mysore Sandalwood and nourishing carrier oils, this conditioning oil tames coarse beard hairs, relieves itchy dry skin underneath, and leaves a premium woody fragrance.",
        ingredients: "Mysore Sandalwood Essential Oil, Cedarwood Extract, Jojoba Oil, Grape Seed Oil, Argan Oil.",
        usage: "Rub 3-5 drops between palms and massage upward into facial hair and onto the skin of the face.",
        features: "Fast absorbing, Prevents beard dandruff, 100% natural oils.",
        price: "$450.00"
    },

    // === KICHEN CARE ===
    {
        id: "sc-1",
        category: "kitchencare",
        badge: "",
        name: "ON&ON Kashmiri Kawah (10 Sachets)",
        image: "images/kitchencare/kashmirikawh.jpeg",
        tag: "Wellness Essential",
        descShort: "Aromatic Ayurvedic green tea that refreshes, energizes, and relieves stress.",
        description: "Unlock premium beauty sleep. These luxury, delicious botanical gummies help synchronize your circadian rhythm, allowing you to wake up looking refreshed, hydrated, and fully energized.",
        ingredients: "Melatonin (3mg), L-Theanine, Chamomile Flower Extract, Lemon Balm, Valerian Root, Pectin base.",
        usage: "Chew 2 gummies 30 minutes before bedtime. Allow at least 7 hours of sleep.",
        features: "Gelatin-free (Vegan), Natural berry flavor, Non-habit forming.",
        price: "$371.00"
    },
    {
        id: "sc-2",
        category: "kitchencare",
        badge: "",
        name: "ON&ON Masala Kawah (10 Tea Bags)",
        image: "images/kitchencare/masalakawah.jpeg",
        tag: "Lifestyle Essential",
        descShort: "Antioxidant-rich Ayurvedic herbal tea that supports immunity and relieves cold and cough.",
        description: "Bring the premium skincare clinic experience home. Emitting 6,000 micro-vibrations per minute, this 24K gold plated T-bar roller drains lymph nodes, contours facial muscles, and lifts saggy skin.",
        ingredients: "24K Gold-Plated Brass Body, Sonic Motor, AA Battery Operated.",
        usage: "Apply your favorite serum, switch on the roller, and glide gently in upward and outward strokes for 5-10 minutes.",
        features: "Waterproof, Travel pouch included, Elegant gift-box packaging.",
        price: "$209.00"
    },
    {
        id: "sc-3",
        category: "kitchencare",
        badge: "",
        name: "Aahar Himalayan Pink Salt (1kg)",
        image: "images/kitchencare/pinksalt.jpeg",
        tag: "Wellness Essential",
        descShort: "Soothing Epsom salts infused with wild Jasmine blossoms and Himalayan pink salt crystals for a restorative bath.",
        description: "Dissolve tension instantly. Our floral bath soak mineralizes skin, relieves muscle soreness, and relaxes the nervous system, enveloping you in a premium floral bouquet scent.",
        ingredients: "Himalayan Pink Salt, Magnesium Sulfate (Epsom Salt), Jasmine Flower Buds, Sweet Almond Oil, Jasmine Essential Oil.",
        usage: "Add half a cup to warm running bath water. Soak for 20 minutes and rinse with clean water.",
        features: "Cruelty-free, 100% pure mineral salts, Hand-blended.",
        price: "$30.00"
    },

    // === AGRI CARE ===
    {
        id: "ac-1",
        category: "agricare",
        badge: "Agri Wellness",
        name: "IndiaGro Mi Veer (250ml)",
        image: "images/agrocare/miveer.jpeg",
        tag: "Soil Wellness",
        descShort: "Organic plant protection solution that controls sucking and chewing pests safely.",
        description: "Presented as modern wellness for farming, our Soil Nutrition Serum rejuvenates depleted agricultural soil, replenishes essential humic substances, and fosters a thriving biological ecosystem.",
        ingredients: "Fulvic Acid extracts, Humic substances, Seaweed kelp concentrates, Beneficial microbial spores.",
        usage: "Dilute 5ml of nutrition serum per liter of water. Drench soil around roots once every two weeks.",
        features: "100% Organic, Safe for all domestic and commercial soils, Non-toxic.",
        price: "$2915.00"
    },
    {
        id: "ac-2",
        category: "agricare",
        badge: "Agri Wellness",
        name: "IndiaGro Modiphy (250ml)",
        image: "images/agrocare/modiphy.jpeg",
        tag: "Foliar Elixir",
        descShort: "Water-soluble pH balancer that improves spray efficiency and nutrient absorption.",
        description: "An elegant, premium organic foliar mist. This growth booster delivers essential botanical growth hormones directly to plant leaves, triggering cellular expansion, root branching, and overall structural vigor.",
        ingredients: "Cold-pressed Neem kernel extracts, Gibberellin extracts, Moringa leaf concentrates, Organic wetting agents.",
        usage: "Spray lightly on plant foliage during early morning or late evening. Repeat every 10 days.",
        features: "Pest repellent action, Natural growth hormones, Zero chemical residues.",
        price: "$550.00"
    },
    {
        id: "ac-3",
        category: "agricare",
        badge: "Agri Wellness",
        name: "IndiaGro Olif Super 16 (500ml)",
        image: "images/agrocare/olif.jpeg",
        tag: "Agri Tool",
        descShort: "16 is a certified organic plant growth promoter that enhances crop yield, strengthens plant immunity, and improves soil health.",
        description: "Ensure your plants thrive in the perfect soil environment. This high-precision sensor requires no batteries, utilizing metal probes to instantly display soil moisture levels and pH levels.",
        ingredients: "Anodized aluminum probes, Copper components, Acrylic read-out display.",
        usage: "Insert the metal probes 3-4 inches into the soil. Switch toggle to pH or moisture, and read the indicator dial.",
        features: "Battery-free operation, Outdoor/Indoor use, Premium carry sleeve.",
        price: "$1430.00"
    }
];
